---
title: "trim"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = ">"
)
```

```{r setup}
library(saferTool2)
```
<br>

### Datasets

```{r}
vec1 <- -1:3 # vector of integers
vec2 <- 1:3 / 3 # vector of proportions
vec3 <- c(1, 2, 3) # vector of integers but stored as "double"
vec4 <- "pearson" # vector of characters
vec5 <- c("a", "b","a", "b") # vector of characters
mat1 <- matrix(vec1) # matrix of integers
mat2 <- matrix(c(1:3 / 3, NA)) # matrix of proportions with NA
```
<br>

### Datasets info

```{r}
vec1 # vector of integers
vec2 # vector of proportions
vec3 # vector of integers but stored as "double"
vec4 # vector of characters
vec5 # vector of characters
mat1 # matrix of integers
mat2 # matrix of proportions with NA
```
<br>

### Simple examples
```{r}
# Check that vec1 is of class integer (means that it is also a vector) -> ok
arg_check(data = vec1, class = "integer")
# Check that vec1 is a numeric vector -> error because vec1 is a vector of integers
arg_check(data = vec1, class = "numeric")
# Check that vec1 is an integer vector of length 3 without negative values and without NA -> error because of length 5 and negative values inside vec1
arg_check(data = vec1, class = "vector", typeof = "integer", length = 3, neg.values = FALSE, na.contain = FALSE)
# No result displayed because the output list is assigned into res (see below the print argument)
res <- arg_check(data = vec1, class = "integer")

# with data = NULL, the function systematically report a checking problem
arg_check(data = NULL, class = "integer")
```
<br>

### Argument prop
```{r}
arg_check(data = mat2, 
    prop = TRUE # Check for values between 0 and 1 only
)
```
<br>

### All the arguments
```{r}
arg_check(data = mat2, 
    prop = TRUE # Check for values between 0 and 1 only
)
```