---
title: "codon_finder"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = ">"
)
```

```{r setup}
library(saferTool2)
```
<br>

### Datasets

```{r}
pos_set1 <- c(3, 7, 9, 12, 15) 
pos_set2 <- c(1, 4, 8, 11, 14)  
pos_set3 <- c(2, 5, 10, 13, 16)  
pos_set4 <- c(6, 13, 17, 19, 20) 
pos_set5 <- c(1, 2, 4, 8, 9)  
begin_value <- 0
end_value <- 20
begin_value2 <- -4
end_value2 <- 22
```
<br>

### Datasets info

```{r}
pos_set1
pos_set2
pos_set3
pos_set4
pos_set5
begin_value
end_value
begin_value2
end_value2
```
<br>

### All the arguments
```{r}
codon_finder(pos = pos_set1, begin = begin_value, end = end_value)
codon_finder(pos = pos_set2, begin = begin_value, end = end_value)
codon_finder(pos = pos_set3, begin = begin_value, end = end_value)
codon_finder(pos = pos_set4, begin = begin_value, end = end_value)
codon_finder(pos = pos_set5, begin = begin_value, end = end_value)
codon_finder(pos = pos_set1, begin = begin_value2, end = end_value2)
codon_finder(pos = pos_set2, begin = begin_value2, end = end_value2)
codon_finder(pos = pos_set3, begin = begin_value2, end = end_value2)
codon_finder(pos = pos_set4, begin = begin_value2, end = end_value2)
codon_finder(pos = pos_set5, begin = begin_value2, end = end_value2)
```