---
title: "permut"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = ">"
)
```

```{r setup}
library(saferTool2)
```
<br>

### Simple example

```{r}
permut(data1 = 1:10, data2 = 10:1, seed = 1, print.count = 1e5, cor.limit = 0.5)
```
<br>

### Example showing that for loop, used in permut(), is faster than while loop

```{r}
ini.time <- as.numeric(Sys.time()) ; 
count <- 0 ; 
for(i0 in 1:1e6){count <- count + 1} ; 
tempo.time <- as.numeric(Sys.time()) ; 
tempo.lapse <- saferTool::round2(as.numeric(lubridate::seconds_to_period(tempo.time - ini.time))) ;
tempo.lapse
```
<br>


### example showing that for loop, used in permut(), is faster than while loop

```{r}
ini.time <- as.numeric(Sys.time()) ; 
count <- 0 ; 
while (count < 100) {count <- count + 1} ; 
tempo.time <- as.numeric(Sys.time()) ; 
tempo.lapse <- saferTool::round2(as.numeric(lubridate::seconds_to_period(tempo.time - ini.time))) ; 
tempo.lapse

permut(data1 = LETTERS[1:5], data2 = NULL, n = 10, seed = 1, print.count = 10, text.print = "CPU NB 4")

permut(data1 = 101:110, data2 = 21:30, seed = 1, print.count = 1e4, text.print = "", cor.method = "spearman", cor.limit = 0.2)
```
<br>



### A way to use the cor.limit argument just considering data1
```{r}
obs1 <- 101:110 ; 
permut(data1 = obs1, data2 = obs1, seed = 1, print.count = 1e6, cor.method = "spearman", cor.limit = 0.2)
```
<br>

