---
title: "slide"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = ">"
)
```

```{r setup}
library(saferTool2)
```
<br>

### Datasets

```{r}
data <- c(1:10, 100:110, 500)
```
<br>

### Datasets info

```{r}
data
```
<br>


### Simple example
```{r}
slide(data = data, window.size = 5, step = 2, FUN  = length)
```
<br>

### Argument from
```{r}
slide(data = data, window.size = 5, step = 2, from = NULL, FUN  = length)
```
<br>

### Argument to
```{r}
slide(data = data, window.size = 5, step = 2, to = NULL, FUN  = length)
```
<br>


### Argument args
```{r}
slide(data = data, window.size = 5, step = 2, FUN  = length, args = NULL)
```
<br>

### Argument boundary
```{r}
slide(data = data, window.size = 5, step = 2, FUN  = length, boundary = "left")
```
<br>

### Argument parall
```{r}
slide(data = data, window.size = 5, step = 2, FUN  = length, parall = FALSE)
```
<br>

### Argument thread.nb
```{r}
slide(data = data, window.size = 5, step = 2, FUN  = length, parall = TRUE, thread.nb = NULL)
```
<br>

### Argument print.count
```{r}
slide(data = data, window.size = 5, step = 2, FUN  = length, print.count = 100)
```
<br>

### Argument res.path
```{r}
slide(data = data, window.size = 5, step = 2, FUN  = length, res.path = NULL)
```
<br>


### Argument lib.path
```{r}
slide(data = data, window.size = 5, step = 2, FUN  = length, lib.path = NULL)
```
<br>


### Argument verbose
```{r}
slide(data = data, window.size = 5, step = 2, FUN  = length, verbose = TRUE)
```
<br>

### Argument verbose
```{r}
slide(data = data, window.size = 5, step = 2, FUN  = length, safer_check = TRUE)
```
<br>

### All the arguments
```{r}
slide(
      data = data,
      window.size = 5,
      step = 2,
      from = NULL,
      to = NULL,
      FUN  = length,
      args = NULL,
      boundary = "left",
      parall = FALSE,
      thread.nb = NULL,
      print.count = 100,
      res.path = NULL,
      lib.path = NULL,
      verbose = TRUE,
      safer_check = TRUE
    )
```

